name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Directory Creation
      run: mkdir build
    - name: CMake Initialization
      run: cd build && cmake ..
    - name: Binary Compilation
      run: cd build && make
